services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9020
    env_file:
      - .env
    depends_on:
      - server
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9020:9020"
    environment:
      - WVHOST=weaviate
      - WVPORT=8080
      - SERVERPORT=9020
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./server:/app/src
      - ./.env:/app/.env
    working_dir: /app
    depends_on:
      weaviate:
        condition: service_healthy
    networks:
      - app_network

  weaviate:
    image: semitechnologies/weaviate:1.26.1
    ports:
      - "9035:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  weaviate_data:
  web_node_modules:

networks:
  app_network:
    driver: bridge